name: gaussiancube
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - python=3.8
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - mpi4py
  - imageio
  - tensorboard
  - pip:
    - trimesh
    - omegaconf
    - plyfile==0.8.1
    - kiui
    - scipy
    - opencv-python
    - imageio-ffmpeg
    - git+https://github.com/graphdeco-inria/diff-gaussian-rasterization.git
